### ISSUE TITLE
Upstream: Installation broken on MacOS with Apple Silicon

### ISSUE THREAD

**Issue by onedrawingperday** [SekouDiaoNlp/mlconjug3#215]
**Describe the bug**

- Installing with `pip` fails as described in https://github.com/lutzroeder/netron/issues/627
- Installing from source is possible but the dependencies `numpy`, `scipy` and `scikit-learn` cannot be built on Apple Silicon, therefore the library cannot run.

Current workaround as described in https://github.com/lutzroeder/netron/issues/627#issuecomment-735882518 is to install the above dependencies with a [Miniforge installer](https://github.com/conda-forge/miniforge#miniforge).

---

Relevant upstream issues:

https://github.com/numpy/numpy/issues/18143
https://github.com/scipy/scipy/issues/13409
https://github.com/scikit-learn/scikit-learn/issues/19137

**Comment by SekouDiaoNlp** [comment]
Hi @onedrawingperday , thanks for letting me know about this issue.
As I do not have a Mac computer with the M1 processor, I was not aware of this compilation problem.

I will add mlconjug3 to conda forge during the week, so that users with the M1 processor will be able to install mlconjug without any hassle as all libraries are already pre-compiled on conda.

I will let you know as soon as mlconjug3 is available in anaconda/miniconda.

Cheers,

Sekou.

**Comment by SekouDiaoNlp** [comment]
Hi @onedrawingperday .

I did the necessary to upload mlconjug3 to conda-forge.

It should take a couple of days before it is available for download.

You should be able to install mlconjug3 directly from conda with pre-compiled dependencies once it is on the conda-forge channel.

I will keep you informed as soon as it is released.

Cheers,

Sekou.

**Comment by SekouDiaoNlp** [comment]
Hello @onedrawingperday !

You can find the pull request for the integration in conda-forge here: [issue 14559 on the conda-forge repository](https://github.com/conda-forge/staged-recipes/pull/14559)

**Comment by SekouDiaoNlp** [comment]
Hi @onedrawingperday how are you today?

I can finally confirm that mlconjug3 is now available on conda-forge.

You can find the website at [conda mlconjug3](https://anaconda.org/conda-forge/mlconjug3).

To install it from conda, type the following commands:

`conda install -c conda-forge mlconjug3`

Would it be possible for you to test that everything works by installing mlconjug3 on a Mac computer with an M1 processor and let me know if everything works accordingly before I close this Pull Request?

Thank you again for letting me know about this issue, I would not have discovered it by myself as I don't have a Mac with anM1 processor handy to make tests.

Cheers,

@SekouDiaoNlp .

**Comment by onedrawingperday** [comment]
Hi @SekouDiaoNlp 

I will check it out during the weekend and let you know.

Thanks!

**Comment by SekouDiaoNlp** [comment]
HI @onedrawingperday. would it be possible for you to both try mlconjug3 version 3.7.15 and 3.7.16 please?

I just want to make sure that the latest 3.7.16 installs correctly on Mac computers with an M1 processor.

Thanks in advance.

@SekouDiaoNlp

**Comment by SekouDiaoNlp** [comment]
HI @onedrawingperday. 

I just wanted to let you know that I just released the latest version of mlconjug3 which is version 3.7.17.

As I designed a new Continuous Integration/ Continuous Delivery pipeline using [GitHub Actions Workflows](https://github.com/SekouDiaoNlp/mlconjug3/actions), I am now able to automatically build, install and test my package on Windows, Linux and MacOS.
Moreover, after uploading and maintaining mlconjug3 on conda-forge, they run every new release through a thorough [CI/CD pipeline on Azure DevOps](https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=12459&_a=summary) building and testing the package not only on different Operating Systems and Python versions, but also on a large array of different processor architecture.

I am pretty confident that if you `conda install -c conda-forge mlconjug3`, you will install the latest version 3.7.17 and everything should build and install properly even on a Computer with an Apple ARM M1 processor.

You don't need to test if versions 3.7.15 and 3.7.16 build and install properly.

If you can just confirm me that 3.7.17 builds, install and works fine on a MacBook with an M1 processor, I will close this Pull Request.

Thanks again for letting me know about this issue and for being willing to test the newest version to confirm it works as expected.

Cheers man,

@SekouDiaoNlp

**Comment by onedrawingperday** [comment]
Hello @SekouDiaoNlp 

I just installed `miniconda` and setup the `conda-forge` channel. 

The latest `mlconjug3` builds fine! 

Thank you so very much! 👍✌️👏

<details><summary>Click to see the conjugation of manger</summary>
<p>
```
mlconjug3 manger                      
{
    "manger": {
        "Infinitif": {
            "Infinitif Présent": "manger"
        },
        "Indicatif": {
            "Présent": {
                "1s": "mange",
                "2s": "manges",
                "3s": "mange",
                "1p": "mangeons",
                "2p": "mangez",
                "3p": "mangent"
            },
            "Imparfait": {
                "1s": "mangeais",
                "2s": "mangeais",
                "3s": "mangeait",
                "1p": "mangions",
                "2p": "mangiez",
                "3p": "mangeaient"
            },
            "Futur": {
                "1s": "mangerai",
                "2s": "mangeras",
                "3s": "mangera",
                "1p": "mangerons",
                "2p": "mangerez",
                "3p": "mangeront"
            },
            "Passé Simple": {
                "1s": "mangeai",
                "2s": "mangeas",
                "3s": "mangea",
                "1p": "mangeâmes",
                "2p": "mangeâtes",
                "3p": "mangèrent"
            }
        },
        "Conditionnel": {
            "Présent": {
                "1s": "mangerais",
                "2s": "mangerais",
                "3s": "mangerait",
                "1p": "mangerions",
                "2p": "mangeriez",
                "3p": "mangeraient"
            }
        },
        "Subjonctif": {
            "Présent": {
                "1s": "mange",
                "2s": "manges",
                "3s": "mange",
                "1p": "mangions",
                "2p": "mangiez",
                "3p": "mangent"
            },
            "Imparfait": {
                "1s": "mangeasse",
                "2s": "mangeasses",
                "3s": "mangeât",
                "1p": "mangeassions",
                "2p": "mangeassiez",
                "3p": "mangeassent"
            }
        },
        "Imperatif": {
            "Imperatif Présent": {
                "2s": "mange",
                "1p": "mangeons",
                "2p": "mangez"
            }
        },
        "Participe": {
            "Participe Présent": "mangeant",
            "Participe Passé": {
                "ms": "mangé",
                "mp": "mangés",
                "fs": "mangée",
                "fp": "mangées"
            }
        }
    }
}
```

</p>
</details>

**Comment by SekouDiaoNlp** [comment]
Hi @onedrawingperday, I hope yo had a great weekend.

Thank you very much for having taken the time to test that the newest version of mlconjug3 available on conda-forge works flawlessly on MacBooks with an ARM M1 processor.

And thank you again for letting me know about this issue in the first place. I really appreciate it!

I also updated the installation instructions in the [documentation](https://mlconjug3.readthedocs.io/en/latest/installation.html#stable-release) to make clear that mlconjug3 can be installed both through:

 `$ pip install mlconjug3` or 

`$ conda config --add channels conda-forge`
`$ conda config --set channel_priority strict`
`$ conda install mlconjug3`

I also added an extra warning note advising users with an ARM M1 computer to install mlconjug3 through conda.

Thank you for your contribution to this project, and do not hesitate to propose changes or enhancement to this package.

By the  way, I am interested in the use case you have for mlconjug3, do you use it as a standalone package to conjugate verbs, or do you use it as a library in your on software?

Peace, love and have fun :heart_eyes:

@SekouDiaoNlp

**Comment by onedrawingperday** [comment]
@SekouDiaoNlp 

Again thank you very much for fixing this! 🙏

My use case is pretty simple:

J'apprends le français 😃

**Comment by SekouDiaoNlp** [comment]
@SekouDiaoNlp , alors bonne chance dans ton apprentissage.

La meilleure façon d'apprendre le français est de pratiquer la langue avec des locuteurs natifs.
(I am French by the way if it was not obvious).

I can advise you to try to have face to face conversations with french speaking people on [Omegle](https://www.omegle.com/),
your comprehension and fluency will improve dramatically if you try to do it a few times a week.

Good luck in your learning and enjoy your life (even though the lockdown due this fu**ing coronavirus is really starting to pissing me off!
### **Γάμα τον κοροναϊό**  :stuck_out_tongue_closed_eyes:

@SekouDiaoNlp
