### ISSUE TITLE
Odd Output - Portuguese

### ISSUE THREAD

**Issue by Jmorr10** [SekouDiaoNlp/mlconjug3#3]
**Describe the bug**
The "1p" of "Indicativo pretérito perfeito simples" always produces odd output with -AR verbs. For example, with the word "pegar", it outputs "peg)". Same thing with "falar" or any other -AR verb. Alternatively, the word might produce a null. "trabalhar" produces **null** in the same spot ("1p" of "Indicativo pretérito perfeito simples"). This bug only affects -AR verbs (-ER and -IR output seems normal). I tested 837 -AR verbs, and every single one of them displayed this issue.

The same behavior occurs in both custom code (i.e., when mlconjug is imported) and when using the command line tool.

**To Reproduce**
1. Run mlconjug pegar -l pt
2. Run mlconjug trabalhar -l pt
3. Run mlconjug comer -l pt
4. Run mlconjug partir -l pt

**Expected behavior**
Pegar --> 1p, Indicativo pretérito perfeito simples = pegamos
Trabalhar --> trabalhamos
Comer --> comemos
Partir --> partimos

**Comment by SekouDiaoNlp** [comment]
Hi @Jmorr10 , thanks for using mlconjug3 and for filing this bug report.

I will investigate this issue and release a new version with the fix as soon as possible.

Cheers,

SekouDiaoNlp.

**Comment by SekouDiaoNlp** [comment]
Hi @Jmorr10 !

I am finally out of lockdown and started looking into your issue.

I am in the process of fixing it and should push a fix tomorrow here on github and will release version 3.7.2 with the fix on PyPi tomorrow.

Sorry for the delay.

I will add a comment to this issue as soon as I upload the new version to PyPi to let you know.

Cheers,

SekouDiaoNlp.

**Comment by SekouDiaoNlp** [comment]
Hi @Jmorr10 !

I just released version 3.7.3 of mlconjug3 on PyPi.

This version fixes the issue with the portuguese verbs.

Now, running mlconjug pegar -l pt or mlconjug trabalhar -l pt gives the expected results for "1p" of "Indicativo pretérito perfeito simples".

Can you check the new version and let me know if it solves the issue for you?

Thanks in advance.

SekouDiaoNlp.
