### ISSUE TITLE
Incorrect gerunds in Spanish

### ISSUE THREAD

**Issue by Perspx** [SekouDiaoNlp/mlconjug3#44]
I was taking a look at [this issue](https://github.com/SekouD/mlconjug/issues/82) from the original mlconjug repository but it looks like Spanish gerunds aren't being conjugated correctly in the latest versions of mlconjug3.

Running the same example as in the original issue:

    import mlconjug3

    default_conjugator = mlconjug3.Conjugator("es")
    conjug_info = default_conjugator.conjugate("correr").conjug_info
    gerund = conjug_info["Gerundio"]
    print(gerund)

Prints:

    OrderedDict([('Gerundio Gerondio', OrderedDict([('', 'corrido')]))])

Is there something I'm missing here? I tried installing mlconjug3 both with `pip` and `setup.py` (and even tried building v3.7.1) and all returned the same results.

Thanks!

**Comment by SekouDiaoNlp** [comment]
Hi @Perspx ,

Thanks for submitting this issue 😃

I will check during the weekend why this problem is persisting and publish a new version with the fix as soon as possible.

Thanks for using mlconjug3, I will keep you informed when I release the fix.

Cheers,

SekouDiaoNlp.

**Comment by SekouDiaoNlp** [comment]
Hi @Perspx !

I just released mlconjug3 version 3.7.5 on PyPi with the fix for this issue with Gerunds (I also fixed a related issue with infinitives in this new version).

You can install the new version with `pip install mlconjug3`

Can you check the new version and let me know if it fixes the issue on your system?

Thanks in advance,

SekouDiaoNlp.

**Comment by Perspx** [comment]
@SekouDiaoNlp Great, thanks for the quick fix! Can confirm it's working now.

**Comment by SekouDiaoNlp** [comment]
@Perspx , that's great!

Thanks again for submitting the issue and do not hesitate to submit a feature request in the future.

Cheers,
SekouDiaoNlp.
