### ISSUE TITLE
convert mlmodel 

### ISSUE THREAD

**Issue by iOSDemoSwift** [SekouDiaoNlp/mlconjug3#51]
how to convert mlmodel and use in ios(swift)?

> **Initialize Conjugator**
model = mlconjug3.Model(vectorizer, feature_reductor, classifier)
conjugator = mlconjug3.Conjugator(lang, model)

> **Training and prediction**
conjugator.model.train(dataset.train_input, dataset.train_labels)
predicted = conjugator.model.predict(dataset.test_input)

> **print('Saving CoreML model')**
coreml_model = coremltools.converters.sklearn.convert(conjugator.model, "input", "output")

**got an error with this:**
from sklearn.preprocessing import Imputer

**sklearn 0.23.0**

**Comment by SekouDiaoNlp** [comment]
Hi @iOSDemoSwift .

Thanks for using mlconjug3.

I will investigate this issue and let you know as soon as I find the solution.

Cheers, SekouDiaoNlp.
